---
- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      yum: name=httpd state=latest
    - name: Instalar Samba
      yum:
        name: samba
        state: latest
    - name: Iniciando los servicios
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - httpd
        - smb
    - name: Abriendo el firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: Copiando contenido para el http
      copy:
        content: "Bienvenido a la web mainsoft"
        dest: /var/www/html/index.html
        mode: 750
